### PR TITLE
Pristine 1.4 sysfs

### PR DESCRIPTION
**Pull request by edugrasa**
Updated to latest pristine-1.4 and fixed merge conflicts

### CODE REVIEW

**Comment by lbergesio** [comment]
@edugrasa I merged @vmaffione  PR and now this one has conflicts, but I think it can be discarded since @vmaffione 's one was based on 1.4 too. Right?

**Comment by edugrasa** [comment]
Don't know, github still tells your branch has conflicts. The PR I issued was to sync it again with 1.4, did I miss anything?

**Comment by lbergesio** [comment]
mmm weird, but github does not allow me to merge this one due to conflicts

**Comment by vmaffione** [comment]
Yes, mine was based on pristine-1.4. Now everything seem ok, isn't it?
Current #820 is mergeable.

2015-12-23 17:59 GMT+01:00 Leonardo Bergesio notifications@github.com:

> mmm weird, but github does not allow me to merge this one due to conflicts
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lbergesio/stack/pull/11#issuecomment-166944607.

## 

Vincenzo Maffione

**Comment by lbergesio** [comment]
current #820 is mergeable, I mean that this very PR is not mergeable to #820 (my branch) now. Do not know the specific conflicts,but  github just does not let me do it. Anyway it should not be necessary due to your PR, which was merged, was based on 1.4 too.

**Comment by vmaffione** [comment]
Ah, sorry, didn't see this PR. Well, let's avoid problems, maybe Eduard can reissue his pull request starting from current lbergesio:pristine-1.4-sysfs

**Comment by vmaffione** [comment]
Or probably just discard this, if nothing has been added. I think something is wrong with this PR, maybe rebsed commits. Let's avoid any possible problems.

**Pull request closed without merging**
